/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 17:59:46 GMT 2017
 */

package br.com.petdelivery.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.controller.IndexController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IndexController_ESTest extends IndexController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IndexController indexController0 = new IndexController();
      String string0 = indexController0.registrarUsuario();
      assertEquals("preLogin/adiciona-usuario", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IndexController indexController0 = new IndexController();
      String string0 = indexController0.registrarPetshop();
      assertEquals("preLogin/adiciona-prestador-petshop", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IndexController indexController0 = new IndexController();
      String string0 = indexController0.registrarAutonomo();
      assertEquals("preLogin/adiciona-prestador-autonomo", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      IndexController indexController0 = new IndexController();
      String string0 = indexController0.listar();
      assertEquals("preLogin/lista", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      IndexController indexController0 = new IndexController();
      String string0 = indexController0.index();
      assertEquals("index", string0);
  }
}
