/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 18:01:14 GMT 2017
 */

package br.com.petdelivery.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.controller.LoginController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LoginController_ESTest extends LoginController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LoginController loginController0 = new LoginController();
      String string0 = loginController0.loginForm();
      assertEquals("preLogin/login", string0);
  }
}
