/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 18:02:45 GMT 2017
 */

package br.com.petdelivery.jdbc;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.ConnectionFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ConnectionFactory_ESTest extends ConnectionFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConnectionFactory.readProperties("jdbc:mysql://");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ConnectionFactory connectionFactory0 = new ConnectionFactory();
  }
}
