/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 26 21:05:00 GMT 2017
 */

package br.com.petdelivery.jdbc;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.petdelivery.jdbc.ConnectionFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ConnectionFactory_ESTest extends ConnectionFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConnectionFactory connectionFactory0 = new ConnectionFactory();
      ConnectionFactory.HOSTNAME = "wtpwebappsESI2017WEB-INFlibconfig.properties";
      // Undeclared exception!
      try { 
        connectionFactory0.getConnection();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.sql.SQLException: No suitable driver found for jdbc:mysql://wtpwebappsESI2017WEB-INFlibconfig.properties/null?useSSL=null
         //
         verifyException("br.com.petdelivery.jdbc.ConnectionFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ConnectionFactory connectionFactory0 = new ConnectionFactory();
      ConnectionFactory.DB_SSL = "";
      // Undeclared exception!
      try { 
        connectionFactory0.getConnection();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.sql.SQLException: No suitable driver found for jdbc:mysql://null/null?useSSL=
         //
         verifyException("br.com.petdelivery.jdbc.ConnectionFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ConnectionFactory connectionFactory0 = new ConnectionFactory();
      ConnectionFactory.DB_NAME = "H+A|\"?";
      // Undeclared exception!
      try { 
        connectionFactory0.getConnection();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.sql.SQLException: No suitable driver found for jdbc:mysql://null/H+A|\"??useSSL=null
         //
         verifyException("br.com.petdelivery.jdbc.ConnectionFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        ConnectionFactory.readProperties((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ConnectionFactory.readProperties("");
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("C:\\Users\\camila\\ACH2027_ESI\\PetDelivery\\Projeto\\teste\\4bGP");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, ";pE4b:l90_W1w=?[");
      ConnectionFactory.readProperties("4bGP");
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ConnectionFactory connectionFactory0 = new ConnectionFactory();
      ConnectionFactory.PROPERTY_FILE = null;
      // Undeclared exception!
      try { 
        connectionFactory0.getConnection();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      FileSystemHandling.shouldAllThrowIOExceptions();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("C:\\Users\\camila\\ACH2027_ESI\\PetDelivery\\Projeto\\teste\\4bGP");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, ";pE4G:l90_W1w=?[");
      ConnectionFactory.readProperties("4bGP");
  }
}
