/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 18:22:45 GMT 2017
 */

package br.com.petdelivery.jdbc.modelo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.modelo.Agenda_Servico;
import java.sql.Date;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Agenda_Servico_ESTest extends Agenda_Servico_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      agenda_Servico0.setObservacao("");
      assertNull(agenda_Servico0.getId_prestador());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      Long long0 = new Long(0L);
      agenda_Servico0.setId_usuario(long0);
      assertNull(agenda_Servico0.getId_servico());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      Long long0 = new Long(1788L);
      agenda_Servico0.setId_servico(long0);
      assertNull(agenda_Servico0.getId_animal());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      Long long0 = new Long(1330L);
      agenda_Servico0.setId_animal(long0);
      assertNull(agenda_Servico0.getHoraInicio());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      Long long0 = new Long(1040L);
      agenda_Servico0.setId_agendamento(long0);
      assertNull(agenda_Servico0.getHoraFim());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      agenda_Servico0.setHoraInicio((String) null);
      assertNull(agenda_Servico0.getId_animal());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      agenda_Servico0.setHoraFim("");
      assertNull(agenda_Servico0.getId_agendamento());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      agenda_Servico0.setDelivery(false);
      assertFalse(agenda_Servico0.isDelivery());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      agenda_Servico0.setDataInicio((Date) null);
      assertNull(agenda_Servico0.getId_agendamento());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      Date date0 = new Date(3553L);
      agenda_Servico0.setDataFim(date0);
      assertNull(agenda_Servico0.getId_animal());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      boolean boolean0 = agenda_Servico0.isDelivery();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      String string0 = agenda_Servico0.getObservacao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      Long long0 = agenda_Servico0.getId_usuario();
      agenda_Servico0.setId_prestador(long0);
      assertNull(agenda_Servico0.getId_servico());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      Long long0 = agenda_Servico0.getId_servico();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      Long long0 = agenda_Servico0.getId_prestador();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      Long long0 = agenda_Servico0.getId_animal();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      Long long0 = agenda_Servico0.getId_agendamento();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      String string0 = agenda_Servico0.getHoraInicio();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      String string0 = agenda_Servico0.getHoraFim();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      Date date0 = agenda_Servico0.getDataInicio();
      assertNull(date0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Agenda_Servico agenda_Servico0 = new Agenda_Servico();
      Date date0 = agenda_Servico0.getDataFim();
      assertNull(date0);
  }
}
