/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 18:24:39 GMT 2017
 */

package br.com.petdelivery.jdbc.modelo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.modelo.Autonomo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Autonomo_ESTest extends Autonomo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      Long long0 = new Long((byte)0);
      autonomo0.setTelefone(long0);
      assertNull(autonomo0.getBairro());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      autonomo0.setRua(" Vca6fIK#.T2+Kg");
      assertNull(autonomo0.getComplemento());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      autonomo0.setNumero((byte)0);
      assertEquals(0, autonomo0.getNumero());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      autonomo0.setNome("");
      assertNull(autonomo0.getCpf());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      byte[] byteArray0 = new byte[1];
      autonomo0.setFoto(byteArray0);
      assertEquals(0, autonomo0.getDdd());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      autonomo0.setExperiencia("-H7v");
      assertNull(autonomo0.getRua());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      autonomo0.setDdd(2932);
      assertEquals(2932, autonomo0.getDdd());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      Long long0 = new Long((-1L));
      autonomo0.setCpf(long0);
      assertNull(autonomo0.getNome());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      autonomo0.setComplemento("");
      assertNull(autonomo0.getBairro());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      autonomo0.setCep("uQ*:P");
      assertNull(autonomo0.getTelefone());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      autonomo0.setBairro("uQ*:P");
      assertNull(autonomo0.getRua());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      Long long0 = autonomo0.getTelefone();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      String string0 = autonomo0.getRua();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      int int0 = autonomo0.getNumero();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      String string0 = autonomo0.getNome();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      byte[] byteArray0 = autonomo0.getFoto();
      assertNull(byteArray0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      String string0 = autonomo0.getExperiencia();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      int int0 = autonomo0.getDdd();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      Long long0 = autonomo0.getCpf();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      String string0 = autonomo0.getComplemento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      String string0 = autonomo0.getCep();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Autonomo autonomo0 = new Autonomo();
      String string0 = autonomo0.getBairro();
      assertNull(string0);
  }
}
