/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 26 21:30:33 GMT 2017
 */

package br.com.petdelivery.jdbc.modelo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.modelo.Busca;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Busca_ESTest extends Busca_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Busca busca0 = new Busca();
      busca0.servico = "l:\",n";
      String string0 = busca0.getServico();
      assertEquals("l:\",n", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Busca busca0 = new Busca();
      busca0.servico = "";
      String string0 = busca0.getServico();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Busca busca0 = new Busca();
      busca0.setPreco(25.11531);
      double double0 = busca0.getPreco();
      assertEquals(25.11531, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Busca busca0 = new Busca();
      busca0.preco = (-429.130689035);
      double double0 = busca0.getPreco();
      assertEquals((-429.130689035), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Busca busca0 = new Busca();
      busca0.nota = null;
      Long long0 = new Long(0L);
      busca0.nota = long0;
      Long long1 = busca0.getNota();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Busca busca0 = new Busca();
      Long long0 = new Long((-1790L));
      busca0.setNota(long0);
      Long long1 = busca0.getNota();
      assertEquals((-1790L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Busca busca0 = new Busca();
      Long long0 = new Long(3532L);
      busca0.nota = long0;
      Long long1 = busca0.getNota();
      assertEquals(3532L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Busca busca0 = new Busca();
      busca0.setNome("1;");
      String string0 = busca0.getNome();
      assertEquals("1;", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Busca busca0 = new Busca();
      busca0.setNome("");
      String string0 = busca0.getNome();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Busca busca0 = new Busca();
      Long long0 = new Long((-151L));
      busca0.setId(long0);
      Long long1 = busca0.getId();
      assertEquals((-151L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Busca busca0 = new Busca();
      Long long0 = new Long(1L);
      busca0.id = long0;
      Long long1 = busca0.getId();
      assertEquals(1L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Busca busca0 = new Busca();
      Long long0 = new Long(3025L);
      busca0.setId(long0);
      Long long1 = busca0.getId();
      assertEquals(3025L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Busca busca0 = new Busca();
      busca0.condicoes = "LZa";
      String string0 = busca0.getCondicoes();
      assertEquals("LZa", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Busca busca0 = new Busca();
      busca0.setCondicoes("");
      String string0 = busca0.getCondicoes();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Busca busca0 = new Busca();
      busca0.setBairro("^g{G9eVL");
      String string0 = busca0.getBairro();
      assertEquals("^g{G9eVL", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Busca busca0 = new Busca();
      busca0.setDelivery(true);
      boolean boolean0 = busca0.isDelivery();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Busca busca0 = new Busca();
      String string0 = busca0.getCondicoes();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Busca busca0 = new Busca();
      String string0 = busca0.getBairro();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Busca busca0 = new Busca();
      String string0 = busca0.getServico();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Busca busca0 = new Busca();
      Long long0 = busca0.getNota();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Busca busca0 = new Busca();
      boolean boolean0 = busca0.isDelivery();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Busca busca0 = new Busca();
      busca0.setBairro("");
      String string0 = busca0.getBairro();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Busca busca0 = new Busca();
      double double0 = busca0.getPreco();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Busca busca0 = new Busca();
      Long long0 = new Long(0L);
      busca0.setId(long0);
      Long long1 = busca0.getId();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Busca busca0 = new Busca();
      Long long0 = busca0.getId();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Busca busca0 = new Busca();
      String string0 = busca0.getNome();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Busca busca0 = new Busca();
      busca0.setServico("8^");
      assertFalse(busca0.isDelivery());
  }
}
