/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 26 21:31:23 GMT 2017
 */

package br.com.petdelivery.jdbc.modelo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.modelo.Petshop;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Petshop_ESTest extends Petshop_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      petshop0.setNome("vQQO ");
      String string0 = petshop0.getNome();
      assertEquals("vQQO ", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      byte[] byteArray0 = new byte[1];
      petshop0.setLogotipo(byteArray0);
      byte[] byteArray1 = petshop0.getLogotipo();
      assertSame(byteArray1, byteArray0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      petshop0.setDescricao("z,)HU");
      String string0 = petshop0.getDescricao();
      assertEquals("z,)HU", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      Long long0 = new Long(1L);
      petshop0.setCnpj(long0);
      Long long1 = petshop0.getCnpj();
      assertEquals(1L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      Long long0 = new Long((-1131L));
      petshop0.setCnpj(long0);
      Long long1 = petshop0.getCnpj();
      assertEquals((-1131L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      byte[] byteArray0 = petshop0.getLogotipo();
      assertNull(byteArray0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      Long long0 = new Long(0L);
      petshop0.setCnpj(long0);
      Long long1 = petshop0.getCnpj();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      petshop0.setDescricao("");
      String string0 = petshop0.getDescricao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      byte[] byteArray0 = new byte[0];
      petshop0.setLogotipo(byteArray0);
      byte[] byteArray1 = petshop0.getLogotipo();
      assertSame(byteArray1, byteArray0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      String string0 = petshop0.getNome();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      Long long0 = petshop0.getCnpj();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      String string0 = petshop0.getDescricao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      petshop0.setNome("");
      String string0 = petshop0.getNome();
      assertEquals("", string0);
  }
}
