/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 18:26:11 GMT 2017
 */

package br.com.petdelivery.jdbc.modelo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.modelo.Petshop;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Petshop_ESTest extends Petshop_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      petshop0.setNome("[4r)YXU1}5| ");
      assertNull(petshop0.getDescricao());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      byte[] byteArray0 = new byte[6];
      petshop0.setLogotipo(byteArray0);
      assertArrayEquals(new byte[] {(byte)0, (byte)0, (byte)0, (byte)0, (byte)0, (byte)0}, byteArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      petshop0.setDescricao((String) null);
      assertNull(petshop0.getDescricao());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      Long long0 = new Long((byte)0);
      petshop0.setCnpj(long0);
      assertNull(petshop0.getDescricao());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      String string0 = petshop0.getNome();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      byte[] byteArray0 = petshop0.getLogotipo();
      assertNull(byteArray0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      String string0 = petshop0.getDescricao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Petshop petshop0 = new Petshop();
      Long long0 = petshop0.getCnpj();
      assertNull(long0);
  }
}
