/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 18:27:39 GMT 2017
 */

package br.com.petdelivery.jdbc.modelo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.modelo.Raca_Animal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Raca_Animal_ESTest extends Raca_Animal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Raca_Animal raca_Animal0 = new Raca_Animal();
      raca_Animal0.setNome("3%#/'A3");
      assertNull(raca_Animal0.getId_tipo());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Raca_Animal raca_Animal0 = new Raca_Animal();
      Long long0 = new Long(1L);
      raca_Animal0.setId_tipo(long0);
      assertEquals(1L, (long)raca_Animal0.getId_tipo());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Raca_Animal raca_Animal0 = new Raca_Animal();
      raca_Animal0.setId_raca((Long) null);
      assertNull(raca_Animal0.getNome());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Raca_Animal raca_Animal0 = new Raca_Animal();
      String string0 = raca_Animal0.getNome();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Raca_Animal raca_Animal0 = new Raca_Animal();
      Long long0 = raca_Animal0.getId_tipo();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Raca_Animal raca_Animal0 = new Raca_Animal();
      Long long0 = raca_Animal0.getId_raca();
      assertNull(long0);
  }
}
