/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 26 21:35:35 GMT 2017
 */

package br.com.petdelivery.jdbc.modelo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.modelo.Servico_Autonomo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Servico_Autonomo_ESTest extends Servico_Autonomo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      servico_Autonomo0.setPreco(1.0);
      double double0 = servico_Autonomo0.getPreco();
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      servico_Autonomo0.setPreco((-2420.0));
      double double0 = servico_Autonomo0.getPreco();
      assertEquals((-2420.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = new Long(1L);
      servico_Autonomo0.setId_servicoAutonomo(long0);
      Long long1 = servico_Autonomo0.getId_servicoAutonomo();
      assertEquals(1L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = new Long((-355L));
      servico_Autonomo0.setId_servicoAutonomo(long0);
      Long long1 = servico_Autonomo0.getId_servicoAutonomo();
      assertEquals((-355L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = new Long(333L);
      servico_Autonomo0.setId_servico(long0);
      Long long1 = servico_Autonomo0.getId_servico();
      assertEquals(333L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = new Long((-1034L));
      servico_Autonomo0.setId_servico(long0);
      Long long1 = servico_Autonomo0.getId_servico();
      assertEquals((-1034L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Boolean boolean0 = new Boolean(true);
      servico_Autonomo0.setDelivery(boolean0);
      Boolean boolean1 = servico_Autonomo0.getDelivery();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Boolean boolean0 = new Boolean("");
      servico_Autonomo0.setDelivery(boolean0);
      Boolean boolean1 = servico_Autonomo0.getDelivery();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = new Long(1L);
      servico_Autonomo0.setCpf(long0);
      Long long1 = servico_Autonomo0.getCpf();
      assertEquals(1L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = new Long(0L);
      servico_Autonomo0.setCpf(long0);
      Long long1 = servico_Autonomo0.getCpf();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = new Long((-1261L));
      servico_Autonomo0.setCpf(long0);
      Long long1 = servico_Autonomo0.getCpf();
      assertEquals((-1261L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = new Long((-3630L));
      servico_Autonomo0.setCpf(long0);
      Long long1 = servico_Autonomo0.getCpf();
      assertEquals((-3630L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      servico_Autonomo0.setCondicoes("lSz!");
      String string0 = servico_Autonomo0.getCondicoes();
      assertEquals("lSz!", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = Long.getLong("", 0L);
      servico_Autonomo0.setId_servico(long0);
      Long long1 = servico_Autonomo0.getId_servico();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = servico_Autonomo0.getId_servico();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = servico_Autonomo0.getCpf();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      servico_Autonomo0.setCondicoes("");
      String string0 = servico_Autonomo0.getCondicoes();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = Long.getLong("", 0L);
      servico_Autonomo0.setId_servicoAutonomo(long0);
      Long long1 = servico_Autonomo0.getId_servicoAutonomo();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      String string0 = servico_Autonomo0.getCondicoes();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Boolean boolean0 = servico_Autonomo0.getDelivery();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = servico_Autonomo0.getId_servicoAutonomo();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      double double0 = servico_Autonomo0.getPreco();
      assertEquals(0.0, double0, 0.01);
  }
}
