/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 26 21:34:33 GMT 2017
 */

package br.com.petdelivery.jdbc.modelo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.modelo.Servico;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Servico_ESTest extends Servico_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Servico servico0 = new Servico();
      servico0.setNome("iH$?");
      String string0 = servico0.getNome();
      assertEquals("iH$?", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Servico servico0 = new Servico();
      Long long0 = new Long(0L);
      servico0.setId_servico(long0);
      Long long1 = servico0.getId_servico();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Servico servico0 = new Servico();
      Long long0 = new Long((-1L));
      servico0.setId_servico(long0);
      Long long1 = servico0.getId_servico();
      assertEquals((-1L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Servico servico0 = new Servico();
      Long long0 = new Long(115L);
      servico0.setId_servico(long0);
      Long long1 = servico0.getId_servico();
      assertEquals(115L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Servico servico0 = new Servico();
      servico0.setNome("");
      String string0 = servico0.getNome();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Servico servico0 = new Servico();
      Long long0 = servico0.getId_servico();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Servico servico0 = new Servico();
      String string0 = servico0.getNome();
      assertNull(string0);
  }
}
