/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 18:29:47 GMT 2017
 */

package br.com.petdelivery.jdbc.modelo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.modelo.Servico_Petshop;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Servico_Petshop_ESTest extends Servico_Petshop_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Servico_Petshop servico_Petshop0 = new Servico_Petshop();
      servico_Petshop0.setPreco(3829.2321351);
      assertEquals(3829.2321351, servico_Petshop0.getPreco(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Servico_Petshop servico_Petshop0 = new Servico_Petshop();
      Long long0 = new Long(464L);
      servico_Petshop0.setId_servicoPetshop(long0);
      assertNull(servico_Petshop0.getId_unidade());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Servico_Petshop servico_Petshop0 = new Servico_Petshop();
      servico_Petshop0.setId_servico((Long) null);
      assertNull(servico_Petshop0.getId_servico());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Servico_Petshop servico_Petshop0 = new Servico_Petshop();
      Boolean boolean0 = new Boolean(false);
      servico_Petshop0.setDelivery(boolean0);
      assertNull(servico_Petshop0.getId_servico());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Servico_Petshop servico_Petshop0 = new Servico_Petshop();
      servico_Petshop0.setCondicoes("");
      assertNull(servico_Petshop0.getCnpj());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Servico_Petshop servico_Petshop0 = new Servico_Petshop();
      servico_Petshop0.setCnpj((Long) null);
      assertNull(servico_Petshop0.getId_unidade());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Servico_Petshop servico_Petshop0 = new Servico_Petshop();
      double double0 = servico_Petshop0.getPreco();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Servico_Petshop servico_Petshop0 = new Servico_Petshop();
      Long long0 = servico_Petshop0.getId_unidade();
      servico_Petshop0.setId_unidade(long0);
      assertNull(servico_Petshop0.getId_servico());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Servico_Petshop servico_Petshop0 = new Servico_Petshop();
      Long long0 = servico_Petshop0.getId_servicoPetshop();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Servico_Petshop servico_Petshop0 = new Servico_Petshop();
      Long long0 = servico_Petshop0.getId_servico();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Servico_Petshop servico_Petshop0 = new Servico_Petshop();
      Boolean boolean0 = servico_Petshop0.getDelivery();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Servico_Petshop servico_Petshop0 = new Servico_Petshop();
      String string0 = servico_Petshop0.getCondicoes();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Servico_Petshop servico_Petshop0 = new Servico_Petshop();
      Long long0 = servico_Petshop0.getCnpj();
      assertNull(long0);
  }
}
