/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 18:29:00 GMT 2017
 */

package br.com.petdelivery.jdbc.modelo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.modelo.Servico_Autonomo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Servico_Autonomo_ESTest extends Servico_Autonomo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      servico_Autonomo0.setPreco(0L);
      assertNull(servico_Autonomo0.getId_servico());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = new Long(0L);
      servico_Autonomo0.setId_servicoAutonomo(long0);
      assertNull(servico_Autonomo0.getCpf());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = new Long(0L);
      servico_Autonomo0.setId_servico(long0);
      assertNull(servico_Autonomo0.getId_servicoAutonomo());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      servico_Autonomo0.setDelivery((Boolean) null);
      assertNull(servico_Autonomo0.getId_servico());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = new Long(0L);
      servico_Autonomo0.setCpf(long0);
      assertNull(servico_Autonomo0.getDelivery());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      servico_Autonomo0.setCondicoes((String) null);
      assertNull(servico_Autonomo0.getCpf());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      double double0 = servico_Autonomo0.getPreco();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = servico_Autonomo0.getId_servicoAutonomo();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = servico_Autonomo0.getId_servico();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Boolean boolean0 = servico_Autonomo0.getDelivery();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      Long long0 = servico_Autonomo0.getCpf();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Servico_Autonomo servico_Autonomo0 = new Servico_Autonomo();
      String string0 = servico_Autonomo0.getCondicoes();
      assertNull(string0);
  }
}
