/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 26 21:37:36 GMT 2017
 */

package br.com.petdelivery.jdbc.modelo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.modelo.Tipo_Animal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Tipo_Animal_ESTest extends Tipo_Animal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Tipo_Animal tipo_Animal0 = new Tipo_Animal();
      tipo_Animal0.setNome("?st :");
      String string0 = tipo_Animal0.getNome();
      assertEquals("?st :", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Tipo_Animal tipo_Animal0 = new Tipo_Animal();
      Long long0 = new Long(1L);
      tipo_Animal0.setId_tipo(long0);
      Long long1 = tipo_Animal0.getId_tipo();
      assertEquals(1L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Tipo_Animal tipo_Animal0 = new Tipo_Animal();
      Long long0 = new Long((-1L));
      tipo_Animal0.setId_tipo(long0);
      Long long1 = tipo_Animal0.getId_tipo();
      assertEquals((-1L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Tipo_Animal tipo_Animal0 = new Tipo_Animal();
      Long long0 = new Long(0L);
      tipo_Animal0.setId_tipo(long0);
      Long long1 = tipo_Animal0.getId_tipo();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Tipo_Animal tipo_Animal0 = new Tipo_Animal();
      String string0 = tipo_Animal0.getNome();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Tipo_Animal tipo_Animal0 = new Tipo_Animal();
      tipo_Animal0.setNome("");
      String string0 = tipo_Animal0.getNome();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Tipo_Animal tipo_Animal0 = new Tipo_Animal();
      Long long0 = tipo_Animal0.getId_tipo();
      assertNull(long0);
  }
}
