/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 18:30:21 GMT 2017
 */

package br.com.petdelivery.jdbc.modelo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.modelo.Tipo_Animal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Tipo_Animal_ESTest extends Tipo_Animal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Tipo_Animal tipo_Animal0 = new Tipo_Animal();
      tipo_Animal0.setNome("");
      assertNull(tipo_Animal0.getId_tipo());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Tipo_Animal tipo_Animal0 = new Tipo_Animal();
      Long long0 = new Long((-1905L));
      tipo_Animal0.setId_tipo(long0);
      assertNull(tipo_Animal0.getNome());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Tipo_Animal tipo_Animal0 = new Tipo_Animal();
      String string0 = tipo_Animal0.getNome();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Tipo_Animal tipo_Animal0 = new Tipo_Animal();
      Long long0 = tipo_Animal0.getId_tipo();
      assertNull(long0);
  }
}
