/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 18:31:18 GMT 2017
 */

package br.com.petdelivery.jdbc.modelo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.modelo.Unidade_Petshop;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Unidade_Petshop_ESTest extends Unidade_Petshop_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setTelefone((Long) null);
      assertEquals(0, unidade_Petshop0.getNumero());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setRua("");
      assertNull(unidade_Petshop0.getComplemento());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setNumero(891);
      assertEquals(891, unidade_Petshop0.getNumero());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setNome("|:(62");
      assertNull(unidade_Petshop0.getId_unidade());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setId_unidade((Long) null);
      assertNull(unidade_Petshop0.getNome());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setDdd((-1299));
      assertEquals((-1299), unidade_Petshop0.getDdd());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setComplemento("r@Q?Y");
      assertNull(unidade_Petshop0.getNome());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = new Long(0L);
      unidade_Petshop0.setCnpj(long0);
      assertEquals(0L, (long)unidade_Petshop0.getCnpj());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setCep("");
      assertNull(unidade_Petshop0.getCnpj());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setBairro("");
      assertEquals(0, unidade_Petshop0.getNumero());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = unidade_Petshop0.getTelefone();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      String string0 = unidade_Petshop0.getRua();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      int int0 = unidade_Petshop0.getNumero();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      String string0 = unidade_Petshop0.getNome();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = unidade_Petshop0.getId_unidade();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      int int0 = unidade_Petshop0.getDdd();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      String string0 = unidade_Petshop0.getComplemento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = unidade_Petshop0.getCnpj();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      String string0 = unidade_Petshop0.getCep();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      String string0 = unidade_Petshop0.getBairro();
      assertNull(string0);
  }
}
