/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 26 21:39:01 GMT 2017
 */

package br.com.petdelivery.jdbc.modelo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.modelo.Unidade_Petshop;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Unidade_Petshop_ESTest extends Unidade_Petshop_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = new Long(0L);
      unidade_Petshop0.setTelefone(long0);
      Long long1 = unidade_Petshop0.getTelefone();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = new Long(1L);
      unidade_Petshop0.setTelefone(long0);
      Long long1 = unidade_Petshop0.getTelefone();
      assertEquals(1L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = new Long((-1026L));
      unidade_Petshop0.setTelefone(long0);
      Long long1 = unidade_Petshop0.getTelefone();
      assertEquals((-1026L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setRua("70W{lxHmQ$w");
      String string0 = unidade_Petshop0.getRua();
      assertEquals("70W{lxHmQ$w", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setRua("");
      String string0 = unidade_Petshop0.getRua();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setNumero(4611);
      int int0 = unidade_Petshop0.getNumero();
      assertEquals(4611, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setNumero((-3424));
      int int0 = unidade_Petshop0.getNumero();
      assertEquals((-3424), int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setNome("'oUA[60V43}]b");
      String string0 = unidade_Petshop0.getNome();
      assertEquals("'oUA[60V43}]b", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = new Long((-3731));
      unidade_Petshop0.setId_unidade(long0);
      Long long1 = unidade_Petshop0.getId_unidade();
      assertEquals((-3731L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = new Long(0L);
      unidade_Petshop0.setId_unidade(long0);
      Long long1 = unidade_Petshop0.getId_unidade();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = new Long(1687L);
      unidade_Petshop0.setId_unidade(long0);
      Long long1 = unidade_Petshop0.getId_unidade();
      assertEquals(1687L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setDdd(2407);
      int int0 = unidade_Petshop0.getDdd();
      assertEquals(2407, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setComplemento("yaymKHN*3a");
      String string0 = unidade_Petshop0.getComplemento();
      assertEquals("yaymKHN*3a", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = new Long(0L);
      unidade_Petshop0.setCnpj(long0);
      Long long1 = unidade_Petshop0.getCnpj();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = new Long(1);
      unidade_Petshop0.setCnpj(long0);
      Long long1 = unidade_Petshop0.getCnpj();
      assertEquals(1L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = new Long((-4644L));
      unidade_Petshop0.setCnpj(long0);
      Long long1 = unidade_Petshop0.getCnpj();
      assertEquals((-4644L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setCep("Azo.");
      String string0 = unidade_Petshop0.getCep();
      assertEquals("Azo.", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setBairro("5YN6:Oo>u|");
      String string0 = unidade_Petshop0.getBairro();
      assertEquals("5YN6:Oo>u|", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      String string0 = unidade_Petshop0.getBairro();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setBairro("");
      String string0 = unidade_Petshop0.getBairro();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = unidade_Petshop0.getCnpj();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setComplemento("");
      String string0 = unidade_Petshop0.getComplemento();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      int int0 = unidade_Petshop0.getDdd();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      String string0 = unidade_Petshop0.getCep();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setCep("");
      String string0 = unidade_Petshop0.getCep();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      String string0 = unidade_Petshop0.getRua();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setDdd((-3731));
      int int0 = unidade_Petshop0.getDdd();
      assertEquals((-3731), int0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      unidade_Petshop0.setNome("");
      String string0 = unidade_Petshop0.getNome();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = unidade_Petshop0.getId_unidade();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      String string0 = unidade_Petshop0.getComplemento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      int int0 = unidade_Petshop0.getNumero();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      Long long0 = unidade_Petshop0.getTelefone();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Unidade_Petshop unidade_Petshop0 = new Unidade_Petshop();
      String string0 = unidade_Petshop0.getNome();
      assertNull(string0);
  }
}
