/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 18:32:15 GMT 2017
 */

package br.com.petdelivery.jdbc.modelo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.modelo.Usuario;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Usuario_ESTest extends Usuario_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      usuario0.setTelefone((-1242L));
      assertEquals((-1242L), usuario0.getTelefone());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      usuario0.setSenha("");
      assertEquals("", usuario0.getSenha());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      usuario0.setRua("");
      assertNull(usuario0.getComplemento());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      usuario0.setNumero((-105));
      assertEquals((-105), usuario0.getNumero());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      usuario0.setNome("");
      assertEquals(0L, usuario0.getTelefone());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      usuario0.setEmail("");
      assertNull(usuario0.getCep());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      usuario0.setDdd((-105));
      assertEquals((-105), usuario0.getDdd());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      usuario0.setCpf(0L);
      assertNull(usuario0.getBairro());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      usuario0.setComplemento("/.[rU6z4m`098G");
      assertNull(usuario0.getEmail());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      usuario0.setCep((String) null);
      assertEquals(0, usuario0.getNumero());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      usuario0.setBairro("nn[5Px:xL2L*");
      assertNull(usuario0.getCep());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      long long0 = usuario0.getTelefone();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      String string0 = usuario0.getSenha();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      String string0 = usuario0.getRua();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      int int0 = usuario0.getNumero();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      String string0 = usuario0.getNome();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      String string0 = usuario0.getEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      int int0 = usuario0.getDdd();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      long long0 = usuario0.getCpf();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      String string0 = usuario0.getComplemento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      String string0 = usuario0.getCep();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      String string0 = usuario0.getBairro();
      assertNull(string0);
  }
}
