/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 18:35:05 GMT 2017
 */

package br.com.petdelivery.jdbc.teste;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.teste.TestaRaca_Animal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TestaRaca_Animal_ESTest extends TestaRaca_Animal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TestaRaca_Animal testaRaca_Animal0 = new TestaRaca_Animal();
  }
}
