/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 26 21:43:45 GMT 2017
 */

package br.com.petdelivery.jdbc.teste;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.petdelivery.jdbc.teste.TestaRaca_Animal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TestaRaca_Animal_ESTest extends TestaRaca_Animal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[7];
      // Undeclared exception!
      try { 
        TestaRaca_Animal.main(stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.sql.SQLException: No suitable driver found for jdbc:mysql://null/null?useSSL=null
         //
         verifyException("br.com.petdelivery.jdbc.ConnectionFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TestaRaca_Animal testaRaca_Animal0 = new TestaRaca_Animal();
  }
}
