/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 18:33:40 GMT 2017
 */

package br.com.petdelivery.jdbc.teste;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.jdbc.teste.TestaConexao;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TestaConexao_ESTest extends TestaConexao_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TestaConexao testaConexao0 = new TestaConexao();
  }
}
