/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 18:40:52 GMT 2017
 */

package br.com.petdelivery.servlet;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.servlet.AdicionaUsuarioServlet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AdicionaUsuarioServlet_ESTest extends AdicionaUsuarioServlet_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AdicionaUsuarioServlet adicionaUsuarioServlet0 = new AdicionaUsuarioServlet();
  }
}
