/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 25 18:39:25 GMT 2017
 */

package br.com.petdelivery.mvc.logica;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.petdelivery.mvc.logica.UsuarioSelectLogic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UsuarioSelectLogic_ESTest extends UsuarioSelectLogic_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UsuarioSelectLogic usuarioSelectLogic0 = new UsuarioSelectLogic();
  }
}
